[package]
name = "regexp01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
regex = "1"
arboard = { version = "3", features = ["wl-clipboard-rs", "image-data"] }
